FROM python:3.10-alpine

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 DJANGO_ENV=production

ARG HOME_DIR=/app
WORKDIR $HOME_DIR

COPY ./docker/scripts/app-entrypoint.sh app-entrypoint.sh
ENTRYPOINT ["./app-entrypoint.sh"]

COPY . .

RUN apk update \
    && apk add build-base postgresql-dev \
    && pip3 install --no-cache-dir --upgrade pip \
    && pip install -r requirements.txt \
    && chmod a+x ./app-entrypoint.sh
