# Generated by Django 4.0.4 on 2022-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_filmwork_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='certificate'),
        ),
    ]
