# Generated by Django 4.0.4 on 2022-06-05 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0007_alter_filmwork_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='rating',
            field=models.FloatField(blank=True, default=0,
                                    validators=[django.core.validators.MinValueValidator(0.0),
                                                django.core.validators.MaxValueValidator(10.0)],
                                    verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(blank=True, choices=[('director', 'director'), ('writer', 'writer'),
                                                        ('actor', 'actor')], default='actor', max_length=10,
                                   null=True, verbose_name='role'),
        ),
    ]
