# Generated by Django 4.0.4 on 2022-06-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_filmwork_rating_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='film_work_person_idx',
        ),
    ]
