# Generated by Django 4.0.4 on 2022-06-04 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0003_rename_created_filmwork_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
    ]
