# Generated by Django 4.0.4 on 2022-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0004_rename_created_genrefilmwork_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['film_work', 'genre'], name='film_work_genre_idx'),
        ),
    ]
